#!/bin/bash

function install_package () {
    local package=$1
    echo $1
    rm -rf install/$package
    rm -rf build/$package
    rm -rf log/$package
    colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --packages-select $package
}

#install_package autoware_parking_srvs
#install_package mission_planner
#install_package parking_route_planner
#install_package freespace_planner
install_package autoware_state_monitor

#install_package costmap_generator
#install_package dummy_perception_publisher
# dummy_perception_publisher
#laserscan_to_occupancy_grid_map

#colcon build --symlink-install --packages-select planning_launch
#colcon build --symlink-install --packages-select simulator_launch
 
