#!/bin/bash
mkdir -p build
{
    echo 'cd build'
    echo 'cmake ..'
    echo 'make -j4'
} > action.sh
chmod +x action.sh

{
    echo '/build'
    echo 'action.sh'
} > .gitignore
echo ''>> CMakeLists.txt # create CMake is not exists

